services:
  pagesense:
    container_name: pagesense
    build:
      context: .
    image: ghcr.io/pranavnbapat/pagesense:latest
    restart: unless-stopped
    cpus: "1.0"
    mem_limit: "2g"
    mem_reservation: "1g"
    environment:
      - GUNICORN_CMD_ARGS=--timeout 720
    ports:
      - "10000:10000"
